SELECT * FROM PF0110.KD_FUNCIONARIO;

--
-- Retira o acesso de select sobre ela kd_funcionario
--
REVOKE SELECT ON PF0110.KD_FUNCIONARIO FROM PUBLIC;

--
-- Concede privilégio de acesso
-- 
GRANT SELECT ON PF0110.KD_FUNCIONARIO TO PUBLIC;


--
-- Selecionando alguns dados com Self Join (Left ou Right Join nesse caso)
--
SELECT F.CD_FUNCIONARIO, 
       F.NM_FUNCIONARIO,
       F.DS_CARGO,
       G.CD_FUNCIONARIO,
       G.NM_FUNCIONARIO,
       G.DS_CARGO CARGO_GESTOR
FROM PF0110.KD_FUNCIONARIO F LEFT JOIN
     PF0110.KD_FUNCIONARIO G
ON (F.CD_GERENTE = G.CD_FUNCIONARIO)
ORDER BY 1;

--
-- Fazer Backup
--
CREATE TABLE T_RHSTU_CONSULTA_BKP AS SELECT * FROM T_RHSTU_CONSULTA;

SELECT COUNT(*) FROM T_RHSTU_CONSULTA_BKP;
SELECT COUNT(*) FROM T_RHSTU_CONSULTA;

--
-- Criando a coluna valor total da consulta na tabela de consulta.
--
ALTER TABLE T_RHSTU_CONSULTA ADD VL_TOT_CONSULTA NUMBER(10,2);

SELECT * FROM T_RHSTU_CONSULTA;
UPDATE T_RHSTU_CONSULTA SET VL_TOT_CONSULTA = DBMS_RANDOM.VALUE(249.33, 500);
COMMIT;


SELECT * FROM T_RHSTU_CONSULTA;


ALTER SESSION SET NLS_DATE_FORMAT = 'DD/MM/YYYY';
SELECT P.ID_PACIENTE,
       P.NM_PACIENTE,
       P.DT_NASCIMENTO,
       TO_CHAR(P.DT_NASCIMENTO, 'MM') MES_NASCIMENTO,
       TO_CHAR(P.DT_NASCIMENTO, 'DD') DIA_NASCIMENTO,
       TO_CHAR(P.DT_NASCIMENTO, 'YYYY') ANO_NASCIMENTO,
       LOWER(P.NM_PACIENTE) NOME_PACIENTE_MINUSCULO,
       UPPER(P.NM_PACIENTE) NOME_PACIENTE_MAIUSCULO,
       INITCAP(P.NM_PACIENTE) NOME_PAC_INICIAIS_MAIUSCULO
FROM   T_RHSTU_PACIENTE P;

UPDATE T_RHSTU_PACIENTE SET NM_PACIENTE = LOWER(NM_PACIENTE);